version: '3'
services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq

  worker1:
    build: ./worker
    environment:
      - RABBITMQ_URL=amqp://rabbitmq

  worker2:
    build: ./worker
    environment:
      - RABBITMQ_URL=amqp://rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
