apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectcrawler-crawler
  labels:
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: projectcrawler-crawler
  template:
    metadata:
      labels:
        app: projectcrawler-crawler
    spec:
      containers:
      - name: projectcrawler-crawler
        image: projectcrawler-crawler:1.0.0
        env:
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq:5672"
        - name: WEBSITES_PATH
          value: "/app/websites"
        volumeMounts:
        - name: websites-volume
          mountPath: /app/websites
      volumes:
      - name: websites-volume
        persistentVolumeClaim:
          claimName: websites-pvc