apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectcrawler-api
  labels:
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projectcrawler-api
  template:
    metadata:
      labels:
        app: projectcrawler-api
    spec:
      containers:
      - name: projectcrawler-api
        image: projectcrawler-api:1.0.0
        ports:
        - containerPort: 3000
        env:
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq:5672"
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/crawler"
        - name: WEBSITES_PATH
          value: "/app/websites"
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch.dev.svc.cluster.local:9200"
        volumeMounts:
        - name: websites-volume
          mountPath: /app/websites
      volumes:
      - name: websites-volume
        persistentVolumeClaim:
          claimName: websites-pvc